include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "coverage/**"
    - ".dart_tool/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"

  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    invalid_annotation_target: ignore # for JsonKey annotations to be used in freezed
    must_be_immutable: ignore
    avoid_types_on_closure_parameters: ignore
    always_specify_types: error
    unused_import: warning
    unused_local_variable: warning
    dead_code: error

linter:
  rules:
    # disable
    use_build_context_synchronously: false
    avoid_renaming_method_parameters: false
    depend_on_referenced_packages: false
    avoid_positional_boolean_parameters: false
    one_member_abstracts: false
    unnecessary_this: false


    # enable
    avoid_print: true
    unnecessary_lambdas: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true
    avoid_setters_without_getters: false
    avoid_returning_null: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    avoid_types_on_closure_parameters: true
    avoid_private_typedef_functions: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_put_control_body_on_new_line: false
    always_use_package_imports: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_parenthesis: true
    unnecessary_await_in_return: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    throw_in_finally: true
