name: wakeme
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '3.13.3'

dependencies:
  flutter:
    sdk: flutter

  # utils
  auto_route: 7.8.3
  flutter_bloc: 8.1.3
  rxdart: 0.27.7
  uuid: 3.0.7
  loggy: 2.0.3
  fpdart: 1.1.0
  easy_debounce: 2.0.3

  # ui
  cupertino_icons: 1.0.6
  enough_platform_widgets: 0.7.3
  draggable_bottom_sheet: 1.0.2
  flutter_hooks: 0.20.3
  intl: 0.18.1

  # l10n
  slang: 3.24.0
  slang_flutter: 3.24.0

  # class management
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # database
  hive: 2.2.3
  path_provider: 2.0.15

  # injection
  get_it: 7.2.0
  injectable: 2.1.1

  time_listener:
    path: "../time_listener"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

  # build_runner generators
  build_runner: 2.3.3
  injectable_generator: 2.1.5
  auto_route_generator: 7.3.1
  freezed: 2.4.1
  json_serializable: 6.7.1
  slang_build_runner: 3.24.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/presentation/fonts/gilroy-semi-bold.ttf
          weight: 600
        - asset: assets/presentation/fonts/gilroy-medium.ttf
          weight: 500
    - family: AlbertSans
      fonts:
        - asset: assets/presentation/fonts/albert-sans-regular.ttf
          weight: 400
