name: wakeme
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '3.1.3'

dependencies:
  flutter:
    sdk: flutter

  # utils
  auto_route: 7.8.3
  flutter_bloc: 8.1.3
  rxdart: 0.27.7
  uuid: 3.0.7
  loggy: 2.0.3
  fpdart: 1.1.0

  # ui
  cupertino_icons: 1.0.6

  # class management
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # database
  hive: 2.2.3
  path_provider: 2.0.15

  # injection
  get_it: 7.2.0
  injectable: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

  # build_runner generators
  build_runner: 2.3.3
  injectable_generator: 2.1.5
  auto_route_generator: 7.3.1
  freezed: 2.4.1
  json_serializable: 6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
