import 'package:flutter/material.dart';

/// colors names generated by [https://colors.artyclick.com/color-name-finder/]

abstract final class CThemeColors {
  static const transparent = Color(0x00000000);
  static const cinder = Color(0xFF141415);
  static const darkJungle = Color(0xFF1C1D1F);
  static const balticSea = Color(0xFF27292A);
  static const carbonGray = Color(0xFF5D5F64);
  static const softPeach = Color(0xFFB1B5B7);
  static const platinum = Color(0xFFE1E3E6);
  static const grayCloud = Color(0xFFEDEEF0);
}
